# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Epsilon' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "Alpha", :path => '../Alpha'
  pod "Alpha/Model", :path => '../Alpha'
  pod "Alpha/Mirror", :path => '../Alpha'
end
